### DISCUSSION TITLE
Using a GitHub Actions build

### DISCUSSION THREAD

**Discussion by MatthewL246** [XaverianTeamRobotics/CenterstageFTCrobotcontroller#25] [Ideas]
We could use [GitHub Actions](https://github.com/features/actions) for continuous integration. It should be pretty easy to create a workflow file to set up a Java environment and build the app. Here is an example `build.yml` file:

```yaml
name: Java Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up the JDK environment
    uses: actions/setup-java@v2
    with:
      java-version: # Whichever version you currently use
      distribution: 'adopt'

  - name: Build with Gradle
    uses: gradle/gradle-build-action@v2
    with:
      arguments: build
```

You could also add linting and formatting if you want to. There might be problems because this is an Android program that relies on the FTC library, but hopefully any problems can be fixed.

Also, I think that we need Mr. Roche to turn on GitHub Actions for the organization. I'm pretty sure that it's free for public repositories.
